/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include <stdio.h>
#include "MyStringConstructor.h"
/* Header for class MyStringConstructor */

JNIEXPORT jstring JNICALL Java_MyStringConstructor_MyNewString
  (JNIEnv *env, jobject obj, jcharArray, jint);

