/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class MyStringConstructor */

#ifndef _Included_MyStringConstructor
#define _Included_MyStringConstructor
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     MyStringConstructor
 * Method:    MyNewString
 * Signature: ([CI)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_MyStringConstructor_MyNewString
  (JNIEnv *, jobject, jcharArray, jint);

#ifdef __cplusplus
}
#endif
#endif
