/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class StaticFieldAccess */

#ifndef _Included_StaticFieldAccess
#define _Included_StaticFieldAccess
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     StaticFieldAccess
 * Method:    accessField
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_StaticFieldAccess_accessField
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
