/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class SystemHandler */

#ifndef _Included_SystemHandler
#define _Included_SystemHandler
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     SystemHandler
 * Method:    print
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_SystemHandler_print
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
