/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class InstanceFieldAccess */

#ifndef _Included_InstanceFieldAccess
#define _Included_InstanceFieldAccess
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     InstanceFieldAccess
 * Method:    accessField
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_InstanceFieldAccess_accessField
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
