/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ShowPID */

#ifndef _Included_ShowPID
#define _Included_ShowPID
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ShowPID
 * Method:    print
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_ShowPID_print
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
